sudo: required
dist: trusty
language: java
cache:
  directories:
    - $HOME/.m2
jdk:
- oraclejdk8

addons:
  chrome: stable

before_install:
  - wget -N http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sleep 3

# whitelist
branches:
    - first-branch    

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - mvn clean install
