sudo: required
dist: trusty
language: java
cache:
  directories:
    - $HOME/.m2
jdk:
- oraclejdk8

addons:
   apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - wget -N http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - "export DISPLAY=99:0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  
  #- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &


# whitelist
branches:
  only:
    - first-branch    

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - mvn clean install
